import { useEffect, useState } from "react";
import { KeyRound, Sparkles, ShieldCheck, Check, Trash2, Terminal } from "lucide-react";
import { PageHeader } from "@/components/ui/PageHeader";
import { GlassCard } from "@/components/ui/GlassCard";
import { toast } from "sonner";
import { api, ApiError, type AiCredentialStatus } from "@/lib/api";
import { apiModels, subscriptionModels, PROVIDER_BASE } from "@/lib/ai-models";
import { setLlmConfigured } from "@/lib/llm";

export function Settings() {
  const [mode, setMode] = useState<"api" | "subscription">("api");
  const [apiKey, setApiKey] = useState(""); const [baseUrl, setBaseUrl] = useState(""); const [model, setModel] = useState(""); const [apiId, setApiId] = useState(apiModels[0].id); const [cliId, setCliId] = useState("");
  const [status, setStatus] = useState<AiCredentialStatus | null>(null); const [busy, setBusy] = useState(false);
  const load = async () => { try { const next = await api.aiCredential(); setStatus(next); setBaseUrl(next.base_url); setModel(next.model); setApiId(apiModels.some((item) => item.id === next.model) ? next.model : "custom"); setLlmConfigured(next.active_source !== "none"); } catch (cause) { toast.error(cause instanceof ApiError ? cause.message : "读取 AI 设置失败"); } };
  useEffect(() => { void load(); }, []);
  const pickApiModel = (id: string) => { const selected = apiModels.find((item) => item.id === id); if (!selected) return; setApiId(id); if (id !== "custom") { setModel(selected.id); setBaseUrl(PROVIDER_BASE[selected.provider] || ""); } };
  const save = async () => { if (!apiKey.trim() || !baseUrl.trim() || !model.trim()) { toast.error("请填写完整的接口地址、模型服务密钥和模型名称"); return; } setBusy(true); try { const next = await api.saveAiCredential(apiKey.trim(), baseUrl.trim(), model.trim()); setStatus(next); setLlmConfigured(true); setApiKey(""); toast.success("个人 API 配置已保存并切换"); } catch (cause) { toast.error(cause instanceof ApiError ? cause.message : "保存失败"); } finally { setBusy(false); } };
  const remove = async () => { setBusy(true); try { await api.deleteAiCredential(); await load(); toast.success("已切回系统默认 AI"); } catch (cause) { toast.error(cause instanceof ApiError ? cause.message : "删除失败"); } finally { setBusy(false); } };
  return <div><PageHeader title="AI 设置" subtitle="系统 AI 默认可用；只有保存个人配置后，当前账户才会切换。" />
    <div className="mb-4 flex items-start gap-2 rounded-lg border border-success/25 bg-success/5 p-3 text-xs text-muted-foreground"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-success" /><span>市场数据无需个人 API。个人密钥加密保存于服务端，不会存入浏览器；删除个人配置即可恢复系统默认。</span></div>
    <div className="mb-4 grid gap-3 sm:grid-cols-2"><GlassCard glow={mode === "subscription"} onClick={() => setMode("subscription")} className={mode === "subscription" ? "ring-1 ring-primary/40" : "opacity-80"}><div className="flex items-center gap-2"><Sparkles className="h-5 w-5 text-primary" /><h3 className="font-semibold">订阅接入</h3>{mode === "subscription" && <Check className="ml-auto h-4 w-4 text-primary" />}</div><p className="mt-1 text-xs text-muted-foreground">使用本机已登录的 AI CLI 订阅额度，无需填写模型服务密钥。</p></GlassCard><GlassCard glow={mode === "api"} onClick={() => setMode("api")} className={mode === "api" ? "ring-1 ring-primary/40" : "opacity-80"}><div className="flex items-center gap-2"><KeyRound className="h-5 w-5 text-primary" /><h3 className="font-semibold">API 接入</h3>{mode === "api" && <Check className="ml-auto h-4 w-4 text-primary" />}</div><p className="mt-1 text-xs text-muted-foreground">填写自己的模型服务密钥，支持预设服务商和任意 OpenAI 兼容端点。</p></GlassCard></div>
    <GlassCard>{mode === "subscription" ? <div className="space-y-3 text-sm"><p className="text-xs text-muted-foreground">选择本机已安装并登录的 CLI。该模式仅适用于本地部署环境。</p><div className="grid gap-2 sm:grid-cols-2">{subscriptionModels.map((item) => <button key={item.id} disabled={item.comingSoon} onClick={() => setCliId(item.id)} className={`flex items-center gap-2.5 rounded-lg border px-3 py-2.5 text-left ${cliId === item.id ? "border-primary/50 bg-primary/10" : "border-border"} ${item.comingSoon ? "cursor-not-allowed opacity-40" : "hover:bg-muted/40"}`}><Terminal className="h-4 w-4 shrink-0 text-muted-foreground" /><div><div className="font-medium">{item.name}{item.comingSoon && <span className="ml-1 text-[10px] text-muted-foreground">即将支持</span>}</div><div className="text-[11px] text-muted-foreground">{item.description}</div></div></button>)}</div><p className="text-xs text-warning">订阅 CLI 的服务端执行通道正在迁移；目前请选择 API 接入，或继续使用系统默认 AI。</p></div> : <div className="space-y-4 text-sm"><label className="block text-xs font-medium text-muted-foreground">选择模型<select value={apiId} onChange={(event) => pickApiModel(event.target.value)} className="mt-1.5 w-full rounded-lg border border-border bg-background px-3 py-2 text-sm">{apiModels.map((item) => <option key={item.id} value={item.id}>{item.name} — {item.description}</option>)}</select></label><label className="block text-xs font-medium text-muted-foreground">接口地址<input value={baseUrl} onChange={(event) => setBaseUrl(event.target.value)} className="mt-1.5 w-full rounded-lg border border-border bg-background px-3 py-2 text-sm" placeholder="https://api.example.com/v1" /></label><label className="block text-xs font-medium text-muted-foreground">模型名称<input value={model} onChange={(event) => setModel(event.target.value)} className="mt-1.5 w-full rounded-lg border border-border bg-background px-3 py-2 text-sm" placeholder="模型名称或接入点 ID" /></label><label className="block text-xs font-medium text-muted-foreground">模型服务密钥<input type="password" value={apiKey} onChange={(event) => setApiKey(event.target.value)} className="mt-1.5 w-full rounded-lg border border-border bg-background px-3 py-2 text-sm" placeholder="sk-…" autoComplete="off" /></label><div className="flex gap-2"><button onClick={() => void save()} disabled={busy} className="rounded-lg bg-primary/15 px-4 py-2 text-sm font-medium text-primary disabled:opacity-50">{busy ? "保存中…" : "保存并切换"}</button>{status?.configured && <button onClick={() => void remove()} disabled={busy} className="inline-flex items-center gap-1.5 rounded-lg px-3 py-2 text-sm text-muted-foreground hover:text-destructive"><Trash2 className="h-4 w-4" />使用系统默认</button>}</div></div>}</GlassCard>
  </div>;
}
